// Everything lives in localStorage on your own phone. No account, no server.

const KEY = 'pantry.v1';

const DEFAULTS = {
  pantry: {},                 // { itemId: qty }   (stock items: 0 out, 1 low, 2 have)
  cookware: ['nonstick_pan', 'saucepan', 'pot'],
  hob: { dialMax: 9, dialMode: 'levels' },  // 'levels' (1..max) or 'watts'
  servings: 1,
  diet: 'egg',
  buy: [],                    // shopping list of item ids
  recent: [],                 // recipe ids, most recent first
  favs: [],
  aiKey: '',
  aiModel: 'claude-opus-5',
  aiRecipes: [],              // recipes generated by Claude, kept locally
  custom: [],                 // your own items that aren't in the library
  theme: 'system',
  seen: false,
};

let state = load();
const subs = new Set();

function load() {
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return structuredClone(DEFAULTS);
    const saved = JSON.parse(raw);
    return { ...structuredClone(DEFAULTS), ...saved, hob: { ...DEFAULTS.hob, ...(saved.hob || {}) } };
  } catch {
    return structuredClone(DEFAULTS);
  }
}

function persist() {
  try { localStorage.setItem(KEY, JSON.stringify(state)); }
  catch (e) { console.warn('Could not save', e); }
}

export const get = () => state;
export function subscribe(fn) { subs.add(fn); return () => subs.delete(fn); }
function emit() { persist(); subs.forEach(fn => fn(state)); }

export function set(patch) { state = { ...state, ...patch }; emit(); }

// ---- shelf ----
export function qty(id) { return state.pantry[id] || 0; }

export function setQty(id, n) {
  const v = Math.max(0, Math.round(n));
  const p = { ...state.pantry };
  if (v === 0) delete p[id]; else p[id] = v;
  state = { ...state, pantry: p };
  emit();
}

export const bump = (id, d) => setQty(id, qty(id) + d);

/** stock items cycle Out -> Have -> Low -> Out */
export function cycleStock(id) {
  const n = qty(id);
  setQty(id, n === 0 ? 2 : n === 2 ? 1 : 0);
}

/** subtract what a recipe used, after you cooked it */
export function consume(uses) {
  const p = { ...state.pantry };
  for (const { id, q, unit } of uses) {
    const have = p[id] || 0;
    if (!have) continue;
    if (unit === 'stock') { if (have === 2 && q) p[id] = 2; continue; }  // jars don't run out per meal
    const left = Math.max(0, have - (q || 0));
    if (left === 0) delete p[id]; else p[id] = left;
  }
  state = { ...state, pantry: p };
  emit();
}

// ---- shopping list ----
export function toggleBuy(id) {
  const has = state.buy.includes(id);
  set({ buy: has ? state.buy.filter(x => x !== id) : [...state.buy, id] });
  return !has;
}
export function addBuy(ids) {
  const merged = [...new Set([...state.buy, ...ids])];
  set({ buy: merged });
}
/** move a bought item onto the shelf */
export function boughtIt(id, n) {
  setQty(id, Math.max(qty(id), n));
  set({ buy: state.buy.filter(x => x !== id) });
}

// ---- kitchen ----
export function toggleCookware(id) {
  const has = state.cookware.includes(id);
  set({ cookware: has ? state.cookware.filter(x => x !== id) : [...state.cookware, id] });
}

export function toggleFav(id) {
  const has = state.favs.includes(id);
  set({ favs: has ? state.favs.filter(x => x !== id) : [...state.favs, id] });
  return !has;
}

export function markCooked(id) {
  set({ recent: [id, ...state.recent.filter(x => x !== id)].slice(0, 12) });
}

export function saveAiRecipe(r) {
  set({ aiRecipes: [r, ...state.aiRecipes.filter(x => x.id !== r.id)].slice(0, 40) });
}

export function wipe() {
  localStorage.removeItem(KEY);
  state = structuredClone(DEFAULTS);
  emit();
}

export function exportJson() {
  return JSON.stringify(state, null, 2);
}

export function importJson(text) {
  const incoming = JSON.parse(text);
  if (!incoming || typeof incoming !== 'object') throw new Error('That file does not look like a Pantry backup.');
  state = { ...structuredClone(DEFAULTS), ...incoming };
  emit();
}
